#Tue Nov 26 11:54:47 EET 2024
junitVersion=5.13.4
junitPlatformVersion=1.11.3
mockitoVersion=5.21.0
keycloakVersion=26.6.3
org.gradle.configuration-cache=true
testContainersKeycloakVersion=4.2.1
testContainersVersion=1.21.4
awaitilityVersion=4.3.0
seleniumRemoteDriverVersion=4.33.0
seleniumVersion=4.33.0
version=1.6.0-SNAPSHOT
jacocoVersion=0.8.13
