name: Publish Package

on:
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    environment: develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Run tests
        run: ./gradlew build test --info